---
functional:
  - Пользователи должны иметь возможность соревноваться друг с другом в написании кода на скорость
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность видеть код своего соперника и вывод тестов
  - Пользователь должен иметь возможность играть против бота
  - Пользователь должен иметь возможность создавать игру и приглашать в неё друзей
  - Пользователь должен иметь возможность присоединяться к игре, созданной другим пользователем
  - Пользователь должен иметь возможность менять язык программирования
  - Игровые задания должны отличаться по уровню сложности
  - Задания должны быть даны на русском и английском языках
  - Пользователь должен иметь возможность наблюдать за матчами других игроков
  - Зарегистрированные пользователи должны иметь возможность общаться в чате
  - Пользователь должен иметь возможность авторизации с использованием эл.почты и пароля, а также посредством профиля в Github и Discord
  - Должна быть реализована система рейтинга игроков за неделю, месяц и всё время
non-functional:
  - Сайт должен быть разработан с учётом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров Google Chrome, Mozilla Firefox, Safari, Yandex, Microsoft Edge, Opera
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Минимальное значение таймера игры должно зависеть от сложности задания
