---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность решать задачу на скорость против бота или другого пользователя
  - Пользователь должен иметь возможность создавать игру и приглашать в неё друзей
  - Пользователь должен иметь возможность присоединяться к играм, созданным другими пользователями
  - В процессе игры пользователь должен иметь возможность наблюдать за ходом решения соперника и выводом тестов, а также менять язык программирования
  - Игровые задания должны отличаться по уровню сложности
  - Пользователь должен иметь возможность выбирать задание
  - Задания должны быть даны на русском и английском языках
  - Пользователь должен иметь возможность наблюдать за матчами других игроков
  - Зарегистрированные пользователи должны иметь возможность общаться в чате
  - Пользователь должен иметь возможность авторизации с использованием эл.почты и пароля, а также посредством профиля в Github и Discord
  - Должна быть реализована система рейтинга игроков за неделю, месяц и всё время
non-functional:
  - Сайт должен быть разработан с учётом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Минимальное значение таймера игры должно зависеть от сложности задания
  - Пользователь должен иметь возможность играть с ботом без регистрации на сайте
  - Пользователь должен иметь возможность создавать новые задания для игр
  - Пользователь должен иметь возможность сдаться во время игры
  - Игроки должны иметь возможность общаться в чате во время выполнения задания
