---
functional:
  - Пользователь должен иметь возможность авторизоваться в системе с использованием эл.почты и пароля, а также посредством профиля в Github и Discord
  - Пользователь должен иметь возможность создавать игру и присоединяться к играм, созданным другими пользователями
  - Пользователь должен иметь возможность наблюдать за играми других пользователей и просматривать их в записи
  - Пользователь должен иметь возможность наблюдать за ходом решения своего соперника и менять язык программирования непосредственно в процессе игры
  - Пользователь должен иметь возможность играть с ботом
non-functional:
  - требование 3
  - требование 4
implicit:
  - требование 5
  - требование 6
