---
functional:
  - Пользователь должен иметь возможность авторизоваться в системе с использованием адреса эл.почты и пароля, а также посредством профиля в Github и Discord
  - требование 2
non-functional:
  - требование 3
  - требование 4
implicit:
  - требование 5
  - требование 6
