---
functional:
  - Пользователь должен иметь возможность авторизации с использованием эл.почты и пароля, а также посредством профиля в Github и Discord
  - Пользователь должен иметь возможность создавать игру и присоединяться к играм, созданным другими пользователями
  - Пользователь должен иметь возможность присоединяться к игре по ссылке
  - Должна быть возможность наблюдать за играми других пользователей и просматривать их в записи
  - У пользователя должна быть возможность наблюдать за ходом решения своего соперника и менять язык программирования непосредственно в процессе игры
  - Пользователь должен иметь возможность играть с ботом без регистрации на сайте
  - Должны составляться рейтинги за неделю, месяц и за всё время
  - Пользователь должен иметь возможность создавать новые задания для игр
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - 
  - требование 6
